// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTMWiGAtQ3dLPJpVE7ZS-aymrslpPGS-c',
    appId: '1:1020071945535:web:d065eab897fe35e3c6df8a',
    messagingSenderId: '1020071945535',
    projectId: 'youeat-97a4b',
    authDomain: 'youeat-97a4b.firebaseapp.com',
    storageBucket: 'youeat-97a4b.appspot.com',
    measurementId: 'G-TNN9KFDHH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlxnM5dSdFTsrWD2LXSrJwgIcjKTBwKfY',
    appId: '1:1020071945535:android:b828eb330e38a448c6df8a',
    messagingSenderId: '1020071945535',
    projectId: 'youeat-97a4b',
    storageBucket: 'youeat-97a4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5QlfAPDwTL6Y4jGHKQpJmfeWmKQkuAC8',
    appId: '1:1020071945535:ios:58dd0808f4a78190c6df8a',
    messagingSenderId: '1020071945535',
    projectId: 'youeat-97a4b',
    storageBucket: 'youeat-97a4b.appspot.com',
    iosClientId: '1020071945535-liouq27ru5scojuct5f849fbjil777rs.apps.googleusercontent.com',
    iosBundleId: 'com.example.youeat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5QlfAPDwTL6Y4jGHKQpJmfeWmKQkuAC8',
    appId: '1:1020071945535:ios:58dd0808f4a78190c6df8a',
    messagingSenderId: '1020071945535',
    projectId: 'youeat-97a4b',
    storageBucket: 'youeat-97a4b.appspot.com',
    iosClientId: '1020071945535-liouq27ru5scojuct5f849fbjil777rs.apps.googleusercontent.com',
    iosBundleId: 'com.example.youeat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTMWiGAtQ3dLPJpVE7ZS-aymrslpPGS-c',
    appId: '1:1020071945535:web:5518a522f605eebdc6df8a',
    messagingSenderId: '1020071945535',
    projectId: 'youeat-97a4b',
    authDomain: 'youeat-97a4b.firebaseapp.com',
    storageBucket: 'youeat-97a4b.appspot.com',
    measurementId: 'G-MNW6E4PMFM',
  );
}
